
HOST = "127.0.0.1"
#UrlFrontier Configuration
#URL_FRONTIER_SERVER_PORT = 2220
#URL_SERVER_PORT = 3693
URL_FRONTIER_SERVER_PORT = 5000
URL_SERVER_PORT = 5001
QUEUE_PATH = "queues/"

#StoreServer Configuration
STORE_SERVER_PORT = 2021
REPO_PATH        = "./Repo/"
